server:
  port: 8761
spring:
  profiles: peer1
  application:
    name: eureka-server1
   
eureka:
  instance:
    hostname: eureka-server-peer1
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
       # defaultZone: http://eureka-server-peer2:8769/eureka/
       #java -jar springcloud_eurekaserver-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
        defaultZone: http://localhost:8769/eureka/