server:
  port: 8769

spring:
  profiles: peer2
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: eureka-server-peer2
  client:
    serviceUrl:
      #defaultZone: http://eureka-server-peer1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/